feat: story09
alem-platform/bootcamp-go pull request #85
Opened 2024-06-10 10:30 UTC by Dias1c

2024-06-11 07:25 UTC, atlekbai requested changes

2024-06-11 07:25 UTC, atlekbai commented on story09/every/README.md
> +```
Здесь `Example output` избыточен, так как в коде в комментариях указан вывод

2024-06-11 07:25 UTC, atlekbai commented on story09/filter/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/for_each/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/get_incrementor/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/get_incrementor/README.md
> +  fmt.Println(anotherIncrementor()) // 16
У тебя тут start работает как `(start, ∞)`, давай переделаем чтобы было `[start, ∞)`

2024-06-11 07:25 UTC, atlekbai commented on story09/is_sorted/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/map_delete_if/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/some/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/sort/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/unite_functions/README.md
> +```
`Example output` избыточен

2024-06-11 07:25 UTC, atlekbai commented on story09/unite_functions/README.md
Как насчет переименовать на `chain_functions`?

2024-06-11 07:25 UTC, atlekbai commented on story09/unite_decorators/README.md
- Предлагаю переименовать на `wrap_function`
- Переписать описание, кажется сложным и непонятно отличие от `unite_functions`
- В Go надо писать `camelCase`

2024-06-11 08:03 UTC, Dias1c commented on story09/get_incrementor/README.md
> +  fmt.Println(anotherIncrementor()) // 16
Обсудили решили оставить как есть

2024-06-12 09:56 UTC, atlekbai requested changes

2024-06-12 09:56 UTC, atlekbai commented on story09/chain_functions/README.md
> +  unitedFunc := ChainFunctions([]func(*string){
`unitedFunc` -> `chainedFunc`

2024-06-12 10:08 UTC, Dias1c commented
Али Апрувнул

2024-06-12 10:08 UTC, merged